#!/usr/bin/env perl
$lualatex = 'lualatex -shell-escape -synctex=1 -interaction=nonstopmode';
$pdflualatex  = $lualatex;
$bibtex = 'bibtex %O %B';
$pdf_mode = 4; # use lualatex
$biber = 'biber --bblencoding=utf8 -u -U --output_safechars';
$max_repeat = 5;
@default_files = ('main.tex');
