
[workspace]
switch = "Control+Option+Command+{N}"
moveTo = "Hyper+{N}"
moveColumnTo = "Unassigned"
focusAnywhere = "Unassigned"
backAndForth = "Control+Option+Command+Tab"
next = "Control+Option+Command+Down Arrow"
previous = "Control+Option+Command+Up Arrow"
swapWithMonitorLeft = "Unassigned"
swapWithMonitorRight = "Unassigned"
swapWithMonitorUp = "Unassigned"
swapWithMonitorDown = "Unassigned"

[focus]
column = "Unassigned"
windowInColumn = "Unassigned"
left = "Control+Option+Command+H"
down = "Control+Option+Command+J"
up = "Control+Option+Command+K"
right = "Control+Option+Command+L"
previous = "Control+Option+Command+Semicolon"
downOrLeft = "Unassigned"
upOrRight = "Unassigned"
windowTop = "Unassigned"
windowBottom = "Unassigned"
windowDownOrTop = "Unassigned"
windowUpOrBottom = "Unassigned"
windowOrWorkspaceDown = "Unassigned"
windowOrWorkspaceUp = "Unassigned"
columnFirst = "Control+Option+Command+Comma"
columnLast = "Control+Option+Command+Period"
monitorNext = "Hyper+Tab"
monitorPrevious = "Unassigned"
monitorLast = "Unassigned"

[move]
columnToIndex = "Unassigned"
left = "Hyper+H"
down = "Hyper+J"
up = "Hyper+K"
right = "Hyper+L"
windowDown = "Unassigned"
windowUp = "Unassigned"
windowDownOrToWorkspaceDown = "Unassigned"
windowUpOrToWorkspaceUp = "Unassigned"
windowToWorkspaceUp = "Hyper+Up Arrow"
windowToWorkspaceDown = "Hyper+Down Arrow"
columnToWorkspaceUp = "Unassigned"
columnToWorkspaceDown = "Unassigned"
columnLeft = "Hyper+Left Arrow"
columnRight = "Hyper+Right Arrow"
columnToFirst = "Hyper+Home"
columnToLast = "Hyper+End"
consumeOrExpelLeft = "Unassigned"
consumeOrExpelRight = "Unassigned"
consumeIntoColumn = "Unassigned"
expelFromColumn = "Unassigned"
"windowToWorkspaceOnMonitor.1.down" = "Unassigned"
"windowToWorkspaceOnMonitor.1.left" = "Unassigned"
"windowToWorkspaceOnMonitor.1.right" = "Unassigned"
"windowToWorkspaceOnMonitor.1.up" = "Unassigned"
"windowToWorkspaceOnMonitor.2.down" = "Unassigned"
"windowToWorkspaceOnMonitor.2.left" = "Unassigned"
"windowToWorkspaceOnMonitor.2.right" = "Unassigned"
"windowToWorkspaceOnMonitor.2.up" = "Unassigned"
"windowToWorkspaceOnMonitor.3.down" = "Unassigned"
"windowToWorkspaceOnMonitor.3.left" = "Unassigned"
"windowToWorkspaceOnMonitor.3.right" = "Unassigned"
"windowToWorkspaceOnMonitor.3.up" = "Unassigned"
"windowToWorkspaceOnMonitor.4.down" = "Unassigned"
"windowToWorkspaceOnMonitor.4.left" = "Unassigned"
"windowToWorkspaceOnMonitor.4.right" = "Unassigned"
"windowToWorkspaceOnMonitor.4.up" = "Unassigned"
"windowToWorkspaceOnMonitor.5.down" = "Unassigned"
"windowToWorkspaceOnMonitor.5.left" = "Unassigned"
"windowToWorkspaceOnMonitor.5.right" = "Unassigned"
"windowToWorkspaceOnMonitor.5.up" = "Unassigned"
"windowToWorkspaceOnMonitor.6.down" = "Unassigned"
"windowToWorkspaceOnMonitor.6.left" = "Unassigned"
"windowToWorkspaceOnMonitor.6.right" = "Unassigned"
"windowToWorkspaceOnMonitor.6.up" = "Unassigned"
"windowToWorkspaceOnMonitor.7.down" = "Unassigned"
"windowToWorkspaceOnMonitor.7.left" = "Unassigned"
"windowToWorkspaceOnMonitor.7.right" = "Unassigned"
"windowToWorkspaceOnMonitor.7.up" = "Unassigned"
"windowToWorkspaceOnMonitor.8.down" = "Unassigned"
"windowToWorkspaceOnMonitor.8.left" = "Unassigned"
"windowToWorkspaceOnMonitor.8.right" = "Unassigned"
"windowToWorkspaceOnMonitor.8.up" = "Unassigned"
"windowToWorkspaceOnMonitor.9.down" = "Unassigned"
"windowToWorkspaceOnMonitor.9.left" = "Unassigned"
"windowToWorkspaceOnMonitor.9.right" = "Unassigned"
"windowToWorkspaceOnMonitor.9.up" = "Unassigned"

[layout]
toggleFullscreen = "Control+Option+Command+Return"
toggleNativeFullscreen = "Hyper+Return"
toggleColumnTabbed = "Control+Option+Command+T"
toggleColumnFullWidth = "Control+Option+Command+F"
expandColumnToAvailable = "Unassigned"
cycleColumnWidthForward = "Control+Option+Command+S"
cycleColumnWidthBackward = "Unassigned"
cycleWindowWidthForward = "Unassigned"
cycleWindowWidthBackward = "Unassigned"
cycleWindowHeightForward = "Unassigned"
cycleWindowHeightBackward = "Unassigned"
decreaseColumnWidth = "Control+Option+Command+A"
increaseColumnWidth = "Control+Option+Command+D"
decreaseWindowWidth = "Unassigned"
increaseWindowWidth = "Unassigned"
decreaseWindowHeight = "Control+Option+Command+X"
increaseWindowHeight = "Control+Option+Command+W"
resetWindowHeight = "Control+Option+Command+R"
balanceSizes = "Control+Option+Command+B"
scrollViewportLeft = "Control+Option+Command+Left Bracket"
scrollViewportRight = "Control+Option+Command+Right Bracket"
toggleFocusedFloating = "Control+Option+Command+Space"
assignScratchpad = "Unassigned"
toggleScratchpad = "Unassigned"
raiseAllFloating = "Hyper+Space"
rescueOffscreen = "Unassigned"

[ui]
commandPalette = "Control+Option+Command+P"
menuAnywhere = "Unassigned"
settings = "Unassigned"
toggleOverview = "Control+Option+Command+O"
toggleWorkspaceBar = "Unassigned"
toggleFocusFollowsMouse = "Unassigned"
toggleFocusFollowsWindowToMonitor = "Unassigned"
toggleMoveMouseToFocused = "Unassigned"
toggleBordersEnabled = "Unassigned"
togglePreventSleepEnabled = "Unassigned"
toggleIPCEnabled = "Unassigned"

[debugging]
dumpRuntimeState = "Unassigned"
resetRuntimeState = "Unassigned"
restartClearingRuntimeState = "Unassigned"
toggleTraceCapture = "Hyper+T"
