[opener]
edit = [
    { run = '${EDITOR:=vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'code "$@"', desc = "VSCode", block = true, for = "unix" },
    { run = 'code "%*"', orphan = true, desc = "code", for = "windows" },
    { run = 'code -w "%*"', block = true,  desc = "code (block)", for = "windows" },
]

view = [
    { run = 'vim -RM "$@"', desc = "readonly", block = true, for = "unix" },
]
